codecov:
  token: 'c73416ae-d5e7-4f6b-9ce9-80829f5a1191'
  require_ci_to_pass: yes
  bot: 'restuwahyu13'
  ci:
    - travis-ci.org
    - appveyor

coverage:
  round: up
  range: '80...100'

parsers:
  javascript:
    enable_partials: yes
